  (setq
       doom-font (font-spec :family (if (eq system-type 'darwin) "Menlo" "DejaVu Sans Mono")
                            :size 14 :weight 'medium)
       fancy-splash-image (concat doom-private-dir "themes/splash.png")
       confirm-kill-emacs nil

  )
  (add-to-list 'default-frame-alist '(inhibit-double-buffering . t))

  ;; Noctalia theme (generated by noctalia-shell user template)
  (add-to-list 'custom-theme-load-path "~/.local/share/noctalia/emacs-themes/")
  (add-hook 'after-init-hook (lambda () (ignore-errors (load-theme 'noctalia t))))
  (set-frame-parameter (selected-frame) 'alpha '(97 . 93))
  ;; (setq! +lookup--last-provider '((fundamental-mode . "Google") (org-mode . "Google") (rust-mode . "Google") (rustic-mode . "Google")))
;; (custom-set-variables
    ;; '(ns-control-modifier 'meta)
    ;; '(ns-command-modifier 'control)
;; '(ns-alternate-modifier 'option)
;; '(ns-option-modifier 'option)
;; )
;; (setq aw-keys '(?n ?e ?i ?o ?m ?u ?y))
(setq-default evil-escape-key-sequence "ii")
(setq-default evil-escape-delay 0.2)
(setq evil-snipe-scope 'buffer)
(defvar toggle-window-maximization t)
(map! :nv "C-M-d"        #'+multiple-cursors/evil-mc-toggle-cursor-here) ;; dumb, but it is what it is
(map! :gnv
      ;; num row
      "C-M-1"            #'+workspace/switch-to-0
      "C-M-2"            #'+workspace/switch-to-1
      "C-M-3"            #'+workspace/switch-to-2
      "C-M-4"            #'+workspace/switch-to-3
      "C-M-5"            #'+workspace/switch-to-4
      "C-M-6"            #'+workspace/switch-to-5
      "C-M-7"            #'+workspace/switch-to-6
      "C-M-8"            #'+workspace:switch-previous
      "C-M-9"            #'+workspace:switch-next
      "C-M-0"            #'+workspace/delete
      ;; top row
      "C-M-q"            #'+workspace/close-window-or-workspace
      "C-M-w"            #'+goto-previous-function.outer
      "C-M-S-w"          #'+goto-previous-class.outer
      "C-M-f"            #'save-buffer
      "C-M-S-f"          #'avy-goto-char-timer
      "C-M-p"            #'scroll-other-window
      "C-M-g"            #'magit-status ;; g

      "C-M-j"            #'+default/diagnostics
      "C-M-S-j"          #'lsp-execute-code-action
      "C-M-l"            #'+lookup/definition
      "C-M-S-l"          #'lsp-rust-find-parent-module
      "C-M-u"            #'+lookup/references
      "C-M-S-u"          #'lsp-rust-analyzer-related-tests
      "C-M-y"            #'consult-imenu-multi
      "C-M-S-y"          #'lsp-ui-imenu
      "C-M-;"            #'lsp-ui-peek--goto-xref-other-window
      "C-M-:"            #'lsp-rust-analyzer-open-external-docs
      ;; mid row
      "C-M-r"            #'+goto-function.outer
      "C-M-S-r"          #'+goto-class.outer
      "C-M-S-s"            #'gptel-send
      ;; "C-M-S-s"          #'gptel-menu
      "C-M-t"            #'scroll-other-window-down
      "C-M-d"            #'+multiple-cursors/evil-mc-toggle-cursor-here

      "M-n"              #'yabai-window-left
      "M-e"              #'yabai-window-down
      "M-i"              #'yabai-window-up
      "M-o"              #'yabai-window-right
      ;; bottom row
      "C-M-v"            #'lsp-extend-selection
      "C-M-b"            #'ranger

      "C-M-k"            #'kill-current-buffer
      "M-RET"            (λ! (if toggle-window-maximization ;; C-M-m, for some reason registered as M-RET
                               (progn (evil-resize-window (- (frame-width) 1) t)
                                      (evil-resize-window (- (frame-width) 1) nil))
                               (balance-windows))
                             (setq toggle-window-maximization (not toggle-window-maximization)))
      "C-M-,"            #'previous-buffer
      "C-M-/"            #'next-buffer
      ;; thumbs
      "M-S-v"          #'+vterm/toggle
      "M-s-v"          #'+vterm/toggle
      "C-M-_"            #'powerthesaurus-hydra/body
)
;; (defhydra +hydra/window-nav (:hint nil) "resize window: _o_:increase width  _n_:decrease width  _i_:increase height  _e_:decrease height _q_:quit"
;;     ("o" evil-window-increase-width)
;;     ("n" evil-window-decrease-width)
;;     ("i" evil-window-increase-height)
;;     ("e" evil-window-decrease-height)
;;     ("q" nil))
(map! :map markdown-mode-map :niv
      "C-M-S-v"          #'+vterm/toggle
      "M-n"              #'aerospace-window-left
      "M-e"              #'aerospace-window-down
      "M-i"              #'aerospace-window-up
      "M-o"              #'aerospace-window-right
      "M-RET"            (λ! (if toggle-window-maximization
                               (progn (evil-resize-window (- (frame-width) 1) t)
                                      (evil-resize-window (- (frame-width) 1) nil))
                               (balance-windows))
                             (setq toggle-window-maximization (not toggle-window-maximization))))
(map! :map vterm-mode-map :niv
      "C-M-S-v"          #'+vterm/toggle
      "M-n"              #'aerospace-window-left
      "M-e"              #'aerospace-window-down
      "M-i"              #'aerospace-window-up
      "M-o"              #'aerospace-window-right
      "M-RET"            (λ! (if toggle-window-maximization
                               (progn (evil-resize-window (- (frame-width) 1) t)
                                      (evil-resize-window (- (frame-width) 1) nil))
                               (balance-windows))
                             (setq toggle-window-maximization (not toggle-window-maximization))))
(map! :map smerge-mode-map :nv
      "n"             #'smerge-prev
      "e"             #'smerge-keep-lower
      "i"             #'smerge-keep-upper
      "o"             #'smerge-next)


(start-process "yabai" nil "yabai" "-m" "window" "--focus" "south")

(defun yabai-move-on-error (direction move-fn)
  (interactive)
  (condition-case nil
      (funcall move-fn)
    (user-error (start-process "yabai" nil "yabai" "-m" "window" "--focus" direction))))


(defun yabai-window-left ()
  (interactive)
  (yabai-move-on-error "west" #'windmove-left))

(defun yabai-window-right ()
  (interactive)
  (yabai-move-on-error "east" #'windmove-right))

(defun yabai-window-up ()
  (interactive)
  (yabai-move-on-error "north" #'windmove-up))

(defun yabai-window-down ()
  (interactive)
  (yabai-move-on-error "south" #'windmove-down))
(defun aerospace-move-on-error (direction move-fn)
  (interactive)
  (condition-case nil
      (funcall move-fn)
    (user-error (start-process "aerospace" nil "aerospace" "focus" direction))))


(defun aerospace-window-left ()
  (interactive)
  (aerospace-move-on-error "left" #'windmove-left))

(defun aerospace-window-right ()
  (interactive)
  (aerospace-move-on-error "right" #'windmove-right))

(defun aerospace-window-up ()
  (interactive)
  (aerospace-move-on-error "up" #'windmove-up))

(defun aerospace-window-down ()
  (interactive)
  (aerospace-move-on-error "down" #'windmove-down))
(use-package! agent-shell
  :commands (agent-shell))
;; we recommend using use-package to organize your init.el
;; (use-package! codeium
;;     ;; if you use straight
;;     ;; :straight '(:type git :host github :repo "Exafunction/codeium.el")
;;     ;; otherwise, make sure that the codeium.el file is on load-path

;;     :init
;;     ;; use globally
;;     (add-to-list 'completion-at-point-functions #'codeium-completion-at-point)
;;     ;; or on a hook
;;     ;; (add-hook 'python-mode-hook
;;     ;;     (lambda ()
;;     ;;         (setq-local completion-at-point-functions '(codeium-completion-at-point))))

;;     ;; if you want multiple completion backends, use cape (https://github.com/minad/cape):
;;     ;; (add-hook 'python-mode-hook
;;     ;;     (lambda ()
;;     ;;         (setq-local completion-at-point-functions
;;     ;;             (list (cape-super-capf #'codeium-completion-at-point #'lsp-completion-at-point)))))
;;     ;; an async company-backend is coming soon!

;;     ;; codeium-completion-at-point is autoloaded, but you can
;;     ;; optionally set a timer, which might speed up things as the
;;     ;; codeium local language server takes ~0.2s to start up
;;     ;; (add-hook 'emacs-startup-hook
;;     ;;  (lambda () (run-with-timer 0.1 nil #'codeium-init)))

;;     ;; :defer t ;; lazy loading, if you want
;;     :config
;;     (setq use-dialog-box nil) ;; do not use popup boxes

;;     ;; if you don't want to use customize to save the api-key

;;     ;; get codeium status in the modeline
;;     (setq codeium-mode-line-enable
;;         (lambda (api) (not (memq api '(CancelRequest Heartbeat AcceptCompletion)))))
;;     (add-to-list 'mode-line-format '(:eval (car-safe codeium-mode-line)) t)
;;     ;; alternatively for a more extensive mode-line
;;     ;; (add-to-list 'mode-line-format '(-50 "" codeium-mode-line) t)

;;     ;; use M-x codeium-diagnose to see apis/fields that would be sent to the local language server
;;     (setq codeium-api-enabled
;;         (lambda (api)
;;             (memq api '(GetCompletions Heartbeat CancelRequest GetAuthToken RegisterUser auth-redirect AcceptCompletion))))
;;     ;; you can also set a config for a single buffer like this:
;;     ;; (add-hook 'python-mode-hook
;;     ;;     (lambda ()
;;     ;;         (setq-local codeium/editor_options/tab_size 4)))

;;     ;; You can overwrite all the codeium configs!
;;     ;; for example, we recommend limiting the string sent to codeium for better performance
;;     (defun my-codeium/document/text ()
;;         (buffer-substring-no-properties (max (- (point) 3000) (point-min)) (min (+ (point) 1000) (point-max))))
;;     ;; if you change the text, you should also change the cursor_offset
;;     ;; warning: this is measured by UTF-8 encoded bytes
;;     (defun my-codeium/document/cursor_offset ()
;;         (codeium-utf8-byte-length
;;             (buffer-substring-no-properties (max (- (point) 3000) (point-min)) (point))))
;;     (setq codeium/document/text 'my-codeium/document/text)
;;     (setq codeium/document/cursor_offset 'my-codeium/document/cursor_offset))
;; accept completion from copilot and fallback to company
;;(use-package! copilot
 ;;:hook (prog-mode . copilot-mode)
;; :bind (("C-TAB" . 'copilot-accept-completion-by-word)
;;        ("C-<tab>" . 'copilot-accept-completion-by-word)
 ;;       :map copilot-completion-map
  ;;      ("<tab>" . 'copilot-accept-completion)
   ;;     ("TAB" . 'copilot-accept-completion)))
;; (use-package! git-link)
(use-package! gptel
 :config
 (setq! gptel-model "gpt-4o-mini")
 (setq  gptel-directives '((default . "You are a large language model living in Emacs and a helpful coding assistant. Respond concisely.")
                         (arbitrage . "As Arbitrage Expert, you specialize in advanced strategies, including cross-exchange trades, in financial markets. Your expertise encompasses risk, spatial, statistical, and triangular arbitrage, with a keen focus on exploiting price discrepancies across different exchanges. Tailored for professionals deeply versed in financial markets, you offer nuanced, data-driven insights into identifying and capitalizing on these opportunities. Your knowledge extends to sophisticated trading algorithms and the latest technologies facilitating efficient cross-exchange arbitrage. Your interactions are analytical and precise, essential for successful arbitrage trading.")
                         (crypto . "As Crypto Commander, you are a specialized GPT model dedicated to advanced and professional-level discourse in the realm of cryptocurrency trading. Your role is to provide high-level, expert insights into cryptocurrency markets, trading strategies, and technological advancements. You cater to users with a deep understanding of cryptocurrency trading, ensuring that interactions remain sophisticated and professional. Your expertise includes detailed analysis of trading indicators, algorithms, and dashboards, tailored for professionals deeply ingrained in the cryptocurrency industry. Your responses are designed to be nuanced and in-depth, suitable for the complex and dynamic world of cryptocurrencies.")
                         (programming . "You are a large language model and a careful programmer. Provide code and only code as output without any additional text, prompt or note.")
                         (writing . "You are a large language model and a writing assistant. Respond concisely.")
                         (chat . "You are a large language model and a conversation partner. Respond concisely.")
                         (rust . "You are expert coder, staff software engineer in fintech company. You are expert at rust, concurrency, multithreading, and async code.")

                         )))
(setq lsp-rust-analyzer-inlay-hints-mode t)
(setq lsp-rust-analyzer-server-display-inlay-hints t)
(setq lsp-ui-sideline-enable nil)
(setq lsp-ui-sideline-show-hover nil)
(setq lsp-ui-peek-always-show t)
(setq magit-todos-mode nil)
(setq! magit-todos-mode nil)
(setq! magit-todos-mode 'nil)
;; (use-package! mermaid-mode)
;; (use-package! mini-modeline
;;   :after smart-mode-line
;;   :config
;;   (mini-modeline-mode t))
;; (use-package! nyan-mode
;;   :config
;;   (nyan-mode 1)
;;   (nyan-start-animation))
;; (use-package! ob-mermaid
;;   :config
;;   (org-babel-do-load-languages 'org-babel-load-languages
;;                               (append org-babel-load-languages
;;                               '((mermaid . t)))))
;; (use-package! org-roam
;;   :after org
;;   :config
;;   (setq org-roam-dailies-directory "Journal/")
;;   (setq org-roam-capture-templates
;;         '(("n" "default" plain "%?"
;;            :target (file+head "pkms/${slug}.org" "${title}\n\n")
;;            :unnarrowed t)
;;           ("j" "new jira ticket" entry "* %?"
;;            :target (file+head+olp "pkms/${slug}.org" "${title}\n#+filetags: ${title}\n\n" ("Inbox"))
;;            :unnarrowed t)
;;           ("q" "question" entry "* [[id:66d7d310-3832-4bf9-9be2-df6e1aeccd61][QUESTION]] %?"
;;            :target (file+head+olp "pkms/${slug}.org" "${title}\n\n" ("Inbox"))
;;            :unnarrowed t)
;;           ("t" "todo" entry "* TODO %?"
;;            :target (file+head+olp "pkms/${slug}.org" "${title}\n\n" ("Inbox"))
;;            :unnarrowed t)))
;; )
;; (use-package! md-roam
;;   :after org-roam
;;   :config
;;   (set-company-backend! 'markdown-mode 'company-capf) ; add company-capf as company backend in markdown buffers
;;   (setq org-roam-file-extensions '("org" "md")) ; enable Org-roam for a markdown files
;;   (md-roam-mode 1) ; md-roam-mode needs to be active before org-roam-db-sync
;;   (org-roam-db-autosync-mode 1)
;;   (add-to-list 'org-roam-capture-templates
;;                '("m" "Markdown" plain "" :target
;;                  (file+head "%<%Y-%m-%dT%H%M%S>-${slug}.md"
;;                             "---\ntitle: ${title}\nid: %<%Y-%m-%dT%H%M%S>\ncategory: \n---\n")
;;                  :unnarrowed t)))

;; (use-package! powerthesaurus)
(setq projectile-project-search-path '("~/Desktop/"))
(use-package! rustic
  :config
  (setq lsp-rust-server 'rust-analyzer)
  (setq rustic-clippy-arguments "--verbose --tests --benches -- -D clippy::all")
  (setq rustic-lsp-server 'rust-analyzer))
(after! lsp-mode
  (setq lsp-inlay-hint-enable t)
  (setq lsp-auto-guess-root nil))
;; (after! rustic
;;   (setq lsp-rust-server 'rust-analyzer)
;;   (setq rustic-lsp-server 'rust-analyzer))
;; (use-package! string-inflection
;;   :config
;;   (map! :n "g C" #'string-inflection-all-cycle)
;; )
; (use-package! switch-window
;;   :config
;;   (setq switch-window-qwerty-shortcuts '("n" "e" "i" "o" "m" "u" "r")))
(add-hook 'python-mode-hook 'ruff-format-on-save-mode)
(add-hook 'python-mode-hook #'flymake-ruff-load)
;; (use-package! vc-msg)
(use-package! which-key
    :config
    (setq which-key-idle-delay 0))
