-- Generated by noctalia — do not edit manually
-- Template inputs: noctalia color tokens (Material You / matugen)
return {
  background    = "{{colors.background.default.hex}}",
  foreground    = "{{colors.on_background.default.hex}}",
  cursor_bg     = "{{colors.primary.default.hex}}",
  cursor_fg     = "{{colors.on_primary.default.hex}}",
  cursor_border = "{{colors.primary.default.hex}}",
  selection_bg  = "{{colors.secondary_container.default.hex}}",
  selection_fg  = "{{colors.on_secondary_container.default.hex}}",
  ansi = {
    "{{colors.surface_container.default.hex}}",        -- black
    "{{colors.error.default.hex}}",                    -- red
    "{{colors.primary.default.hex}}",                  -- green
    "{{colors.secondary.default.hex}}",                -- yellow
    "{{colors.tertiary.default.hex}}",                 -- blue
    "{{colors.secondary_fixed_dim.default.hex}}",      -- magenta
    "{{colors.tertiary_fixed_dim.default.hex}}",       -- cyan
    "{{colors.on_surface.default.hex}}",               -- white
  },
  brights = {
    "{{colors.outline.default.hex}}",                  -- bright black (grey)
    "{{colors.error_container.default.hex}}",          -- bright red
    "{{colors.primary_fixed_dim.default.hex}}",        -- bright green
    "{{colors.tertiary.default.hex}}",                 -- bright yellow
    "{{colors.primary_fixed_dim.default.hex}}",        -- bright blue
    "{{colors.secondary_fixed_dim.default.hex}}",      -- bright magenta
    "{{colors.tertiary_fixed_dim.default.hex}}",       -- bright cyan
    "{{colors.on_background.default.hex}}",            -- bright white
  },
}
